create table public.questions (
  id bigint generated by default as identity primary key,
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  correct_answer text not null check (correct_answer in ('a', 'b', 'c')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Optional: Add an index for faster retrieval if you plan to search/filter
create index questions_created_at_idx on public.questions (created_at);